import os
import sys
import json
import asyncio
import requests
from colorama import Fore, Style, init

sys.stdout.reconfigure(encoding='utf-8')

init(autoreset=True)

CONFIG_FILE = "compress_config.json"

def download_file(url):
    print(Fore.CYAN + "📥 جاري تحميل الفيديو من الرابط...")
    local_filename = url.split('/')[-1]
    if "?" in local_filename: local_filename = local_filename.split("?")[0]
    if not local_filename: local_filename = "downloaded_video.mp4"
    
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        total_length = r.headers.get('content-length')
        with open(local_filename, 'wb') as f:
            if total_length is None: # no content length header
                f.write(r.content)
            else:
                dl = 0
                total_length = int(total_length)
                for chunk in r.iter_content(chunk_size=8192):
                    if chunk:
                        dl += len(chunk)
                        f.write(chunk)
                        done = int(50 * dl / total_length)
                        print(f"\r{Fore.YELLOW}[{'█' * done}{'.' * (50-done)}] {dl*100/total_length:.1f}%", end='')
    print(Fore.GREEN + f"\n✅ تم التحميل: {local_filename}")
    return local_filename

async def upload_to_telegram(file_path):
    from pyrogram import Client
    
    with open(CONFIG_FILE, "r", encoding="utf-8") as f:
        cfg = json.load(f)
        
    api_id = cfg.get("telegram_api_id")
    api_hash = cfg.get("telegram_api_hash")
    bot_token = cfg.get("telegram_token")
    target_chat_id = cfg.get("telegram_chat_id_project_notify", cfg.get("telegram_chat_id"))
    
    if not api_id or not api_hash:
        print(Fore.RED + "❌ بيانات الـ API مش موجودة في الكونفيج!")
        return

    async def progress(current, total):
        pct = current * 100 / total
        print(f"\r{Fore.MAGENTA}🚀 جاري الرفع لتليجرام (يدعم حتى 2GB): {pct:.1f}%", end="")
            
    print(Fore.CYAN + "\n☁️ بدء الاتصال بتيليجرام...")
    
    # Using Pyrogram user session
    app = Client("my_user_session", api_id=api_id, api_hash=api_hash)
    
    async with app:
        print(Fore.CYAN + f"📤 بيتم حاليا الرفع لجروب PROJECT NOTIFY ({target_chat_id}) ...")
        
        try:
            chat_id_to_use = int(target_chat_id)
        except (ValueError, TypeError):
            chat_id_to_use = target_chat_id
            
        await app.send_document(
            chat_id=chat_id_to_use,
            document=file_path,
            caption="🧪 تجربة للنظام الجديد: الرفع المباشر للأحجام الكبيرة (مستند الاختبار)",
            file_name=os.path.basename(file_path),
            progress=progress
        )
        print()
        print(Fore.GREEN + "🎉 تم الرفع بنجاح 100%!")

def main():
    print(Fore.WHITE + Style.BRIGHT + "================================================")
    print("برنامج اختبار رفع الفيديوهات الكبيرة لتليجرام (حتى 2 جيجا)")
    print("================================================")
    print(Fore.YELLOW + "▶️ ملحوظة: يمكنك نسخ (رابط فيديو من النت) أو (مسار فيديو من جهازك).")
    if len(sys.argv) > 1:
        link = sys.argv[1].strip().strip('"')
        print(f"تم إدخال المسار: {link}")
    else:
        link = input("مسار/رابط الفيديو: ").strip().strip('"')
    
    if not link:
        print(Fore.RED + "❌ لم يتم إدخال رابط أو مسار.")
        return

    file_to_upload = link
    is_url = link.startswith("http://") or link.startswith("https://")
    
    if is_url:
        try:
            file_to_upload = download_file(link)
        except Exception as e:
            print(Fore.RED + f"❌ فشل التحميل: {e}")
            return
    elif not os.path.exists(file_to_upload):
        print(Fore.RED + "❌ المسار غير صحيح أو الملف مش موجود عندك ع الجهاز!")
        return

    # Install packages just in case it's the first time
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    
    try:
        import pyrogram
    except ImportError:
        print(Fore.YELLOW + "جاري تسطيب مكتبة تليجرام (pyrogram)...")
        os.system(f"{sys.executable} -m pip install pyrogram")
        
    file_size_mb = os.path.getsize(file_to_upload) / (1024 * 1024)
    print(Fore.CYAN + f"\n📦 حجم الملف اللي هيترفع: {file_size_mb:.1f} MB")
    
    try:
        loop.run_until_complete(upload_to_telegram(file_to_upload))
    except Exception as e:
        print(Fore.RED + f"\n❌ حصلت مشكلة وقت الرفع: {e}")
        
    if is_url and os.path.exists(file_to_upload):
        del_choice = input(Fore.YELLOW + "\nهل تريد مسح الملف اللي نزلناه من النت للتجربة بعد ما رفعناه؟ (y/n): ")
        if del_choice.lower() == 'y':
            os.remove(file_to_upload)
            print(Fore.GREEN + "🗑️ تم المسح.")
            
    # Clean up the session file generated by Pyrogram
    if os.path.exists("test_session_for_upload.session"):
        try:
            os.remove("test_session_for_upload.session")
        except:
            pass

if __name__ == "__main__":
    main()
